#!/usr/bin/env ruby

require "optparse"
require_relative "lib/main"

opts = {}
# required_opts = []
file = nil

parser = OptionParser.new
parser.banner = "Usage: mdr MARKDOWN_FILE_PATH [options]"
parser.separator ""
parser.separator "Options:"
{
  width: ["-w", "--width=COLS", Integer, "Max output width"],
  margin: ["-m", "--margin=NUMBER", Integer, "Global margin (lines are divided by 2)"],
  margin_top: ["-t", "--margin-top=LINES", Integer, "Top margin"],
  margin_bottom: ["-b", "--margin-bottom=LINES", Integer, "Bottom margin"],
  margin_left: ["-l", "--margin-left=COLS", Integer, "Left margin"],
  # margin_right: ["-r", "--margin-right=COLS", Integer, "Right margin"],
  center: ["-c", "--center", "Center output (use with --width)", "Left & right margins are ignored"]
}.each do |name, args|
  parser.on(*args)
end

parser.order!(into: opts) do |non_opt_argv|
  # This block is yielded only for non-options command line arguments
  raise "Unknown additionnal argument: #{non_opt_argv}" if file
  raise "File not found: #{non_opt_argv}" unless File.exist?(non_opt_argv)

  file = non_opt_argv
end

raise "File not provided" unless file

raise "Please specify --width when using --center" if opts[:center] && !opts[:width]

Main.new(file, **opts)
